# Linear Regression in PyTorch


<a href="https://colab.research.google.com/github/ahmedabdelhameed/PyTorch/blob/master/Linear_Regression.ipynb" target="_parent">
    <img src="https://colab.research.google.com/assets/colab-badge.svg"/>


In [1]:
import numpy as np
import torch

In [2]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [5]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad = True)
print(w)
print(b)

tensor([[-0.4506,  0.0775,  0.8138],
        [ 1.4167,  1.2544, -1.2968]], requires_grad=True)
tensor([ 0.9753, -0.5384], requires_grad=True)


In [6]:
def model(x):
  return x @ w.t() +b

In [7]:
preds = model(inputs)

In [8]:
print(preds)

tensor([[  8.2684, 131.1671],
        [ 18.8755, 155.7783],
        [ 19.3584, 215.5960],
        [-11.5410, 149.9270],
        [ 34.2912, 126.8646]], grad_fn=<AddBackward0>)


In [9]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [10]:
#MSE
def mse (t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff) / diff.numel()

In [11]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(4829.0654, grad_fn=<DivBackward0>)


In [12]:
# Compute gradients
loss.backward()

In [13]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-0.4506,  0.0775,  0.8138],
        [ 1.4167,  1.2544, -1.2968]], requires_grad=True)
tensor([[-5193.7305, -6011.0518, -3571.6550],
        [ 5739.4175,  5119.4824,  3131.0769]])


In [14]:
print(b)
print(b.grad)

tensor([ 0.9753, -0.5384], requires_grad=True)
tensor([-62.3495,  63.8666])


In [15]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [16]:
#Adjust weights and biases using gradient descent
preds = model(inputs)
print(preds)

tensor([[  8.2684, 131.1671],
        [ 18.8755, 155.7783],
        [ 19.3584, 215.5960],
        [-11.5410, 149.9270],
        [ 34.2912, 126.8646]], grad_fn=<AddBackward0>)


In [17]:
#compute loss
loss = mse (preds, targets)
print(loss)

tensor(4829.0654, grad_fn=<DivBackward0>)


In [18]:
#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-5193.7305, -6011.0518, -3571.6550],
        [ 5739.4175,  5119.4824,  3131.0769]])
tensor([-62.3495,  63.8666])


In [19]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [20]:
print(w)
print(b)

tensor([[-0.3986,  0.1376,  0.8496],
        [ 1.3593,  1.2032, -1.3281]], requires_grad=True)
tensor([ 0.9759, -0.5391], requires_grad=True)


In [21]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(3509.9019, grad_fn=<DivBackward0>)


In [22]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [23]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(394.2370, grad_fn=<DivBackward0>)


In [24]:
preds

tensor([[ 58.9406,  76.9152],
        [ 86.1026,  88.6417],
        [106.9819, 149.6928],
        [ 30.7223,  74.2786],
        [103.2643,  76.3595]], grad_fn=<AddBackward0>)

In [25]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [26]:
import torch.nn as nn

In [27]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [28]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [29]:
from torch.utils.data import TensorDataset

In [30]:
train_ds = TensorDataset(inputs, targets)

In [31]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [32]:
from torch.utils.data import DataLoader

In [33]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [34]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    #break

tensor([[ 91.,  88.,  64.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 87., 134.,  58.]])
tensor([[ 81., 101.],
        [ 56.,  70.],
        [ 22.,  37.],
        [ 56.,  70.],
        [119., 133.]])
tensor([[ 87., 134.,  58.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.]])
tensor([[119., 133.],
        [ 81., 101.],
        [103., 119.],
        [ 56.,  70.],
        [103., 119.]])
tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 87., 134.,  58.],
        [ 69.,  96.,  70.],
        [102.,  43.,  37.]])
tensor([[ 81., 101.],
        [ 22.,  37.],
        [119., 133.],
        [103., 119.],
        [ 22.,  37.]])


In [35]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1752, -0.0149,  0.2615],
        [-0.1805, -0.2871,  0.4545]], requires_grad=True)
Parameter containing:
tensor([-0.1681,  0.0339], requires_grad=True)


In [36]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1752, -0.0149,  0.2615],
         [-0.1805, -0.2871,  0.4545]], requires_grad=True),
 Parameter containing:
 tensor([-0.1681,  0.0339], requires_grad=True)]

In [37]:
preds = model(inputs)

In [38]:
preds

tensor([[ 22.8680, -12.8357],
        [ 31.2004, -12.5697],
        [ 28.2440, -27.7795],
        [ 26.7380, -13.9080],
        [ 28.7956,  -8.1680],
        [ 22.8680, -12.8357],
        [ 31.2004, -12.5697],
        [ 28.2440, -27.7795],
        [ 26.7380, -13.9080],
        [ 28.7956,  -8.1680],
        [ 22.8680, -12.8357],
        [ 31.2004, -12.5697],
        [ 28.2440, -27.7795],
        [ 26.7380, -13.9080],
        [ 28.7956,  -8.1680]], grad_fn=<AddmmBackward>)

In [39]:
import torch.nn.functional as F

In [40]:
loss_fn = F.mse_loss

In [41]:
loss = loss_fn(model(inputs), targets)

In [42]:
print(loss)

tensor(8171.6299, grad_fn=<MseLossBackward>)


In [45]:
opt = torch.optim.SGD(model.parameters,lr=1e-5)

In [53]:
#Train a model

def fit(num_epochs, model, loss_fn, opt, train_dl):

  #go into a loop for a certain number of epochs
  for epoch in range(num_epochs):

    #for each batch of input and targets
    for xb, yb in train_dl:

      #Step#1 Generate preiction
      preds = model(xb)

      #Step#2 Calculate loss
      loss = loss_fn(preds, yb)

      #Step#3 Compute gradients
      loss.backward()

      #Step#4 Update weights and biases using gradients using single optimization step
      opt.step()

      #Step#5 Reset the gradients to zero
      opt.zero_grad()


      # Print the progress
      if (epoch+1) % 10 == 0:
        print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [54]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 637.4753
Epoch [10/100], Loss: 149.0433
Epoch [10/100], Loss: 62.8873
Epoch [20/100], Loss: 197.8039
Epoch [20/100], Loss: 304.6401
Epoch [20/100], Loss: 63.9667
Epoch [30/100], Loss: 59.4576
Epoch [30/100], Loss: 221.1869
Epoch [30/100], Loss: 110.7162
Epoch [40/100], Loss: 129.7036
Epoch [40/100], Loss: 52.2818
Epoch [40/100], Loss: 89.0741
Epoch [50/100], Loss: 97.6824
Epoch [50/100], Loss: 61.4709
Epoch [50/100], Loss: 23.0399
Epoch [60/100], Loss: 47.5042
Epoch [60/100], Loss: 34.6245
Epoch [60/100], Loss: 43.6705
Epoch [70/100], Loss: 29.2052
Epoch [70/100], Loss: 27.8113
Epoch [70/100], Loss: 29.5644
Epoch [80/100], Loss: 20.1398
Epoch [80/100], Loss: 16.5588
Epoch [80/100], Loss: 24.4178
Epoch [90/100], Loss: 6.9744
Epoch [90/100], Loss: 18.2563
Epoch [90/100], Loss: 18.4065
Epoch [100/100], Loss: 15.0664
Epoch [100/100], Loss: 8.9576
Epoch [100/100], Loss: 7.1713


In [55]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.1881,  71.1185],
        [ 81.8783, 100.9626],
        [117.4116, 130.8068],
        [ 27.3943,  41.8068],
        [ 97.6591, 116.8709],
        [ 58.1881,  71.1185],
        [ 81.8783, 100.9626],
        [117.4116, 130.8068],
        [ 27.3943,  41.8068],
        [ 97.6591, 116.8709],
        [ 58.1881,  71.1185],
        [ 81.8783, 100.9626],
        [117.4116, 130.8068],
        [ 27.3943,  41.8068],
        [ 97.6591, 116.8709]], grad_fn=<AddmmBackward>)

In [56]:

# Compare with targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])