In [57]:
import numpy as np
import torch


In [58]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [59]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [60]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [61]:
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad = True)
print(w)
print(b)

tensor([[-1.6964, -0.5325, -2.3138],
        [ 0.8750,  0.1947, -2.1018]], requires_grad=True)
tensor([-0.0774, -0.6501], requires_grad=True)


In [62]:
def model(x):
  return x @ w.t() +b

In [63]:
preds = model(inputs)

In [64]:
print(preds)

tensor([[-259.0846,  -14.1090],
        [-349.3919,  -38.4088],
        [-353.2184,  -20.3427],
        [-281.6171,   19.2050],
        [-330.2142,  -68.7125]], grad_fn=<AddBackward0>)


In [65]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [66]:
#MSE
def mse (t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff) / diff.numel()

In [67]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(87293.9375, grad_fn=<DivBackward0>)


In [68]:
# Compute gradients
loss.backward()

In [69]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-1.6964, -0.5325, -2.3138],
        [ 0.8750,  0.1947, -2.1018]], requires_grad=True)
tensor([[-32822.1133, -35381.3047, -22008.2422],
        [ -9386.8477, -11447.3574,  -7046.2041]])


In [70]:
print(b)
print(b.grad)

tensor([-0.0774, -0.6501], requires_grad=True)
tensor([-390.9052, -116.4736])


In [71]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [72]:
#Adjust weights and biases using gradient descent
preds = model(inputs)
print(preds)

tensor([[-259.0846,  -14.1090],
        [-349.3919,  -38.4088],
        [-353.2184,  -20.3427],
        [-281.6171,   19.2050],
        [-330.2142,  -68.7125]], grad_fn=<AddBackward0>)


In [73]:
#compute loss
loss = mse (preds, targets)
print(loss)

tensor(87293.9375, grad_fn=<DivBackward0>)


In [74]:
#compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[-32822.1133, -35381.3047, -22008.2422],
        [ -9386.8477, -11447.3574,  -7046.2041]])
tensor([-390.9052, -116.4736])


In [75]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [76]:
print(w)
print(b)

tensor([[-1.3682, -0.1787, -2.0937],
        [ 0.9689,  0.3092, -2.0314]], requires_grad=True)
tensor([-0.0734, -0.6489], requires_grad=True)


In [77]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(59228.6992, grad_fn=<DivBackward0>)


In [78]:
for i in range(100):
  preds = model(inputs)
  loss = mse(preds, targets)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [79]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(647.5021, grad_fn=<DivBackward0>)


In [80]:
preds

tensor([[ 59.2493,  78.5063],
        [ 70.6085,  88.3066],
        [141.7207, 147.8968],
        [ 31.9386,  83.4832],
        [ 75.3963,  70.3849]], grad_fn=<AddBackward0>)

In [81]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [82]:
import torch.nn as nn

In [83]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], [91, 88, 64], [87, 134, 58], 
                   [102, 43, 37], [69, 96, 70], [73, 67, 43], 
                   [91, 88, 64], [87, 134, 58], [102, 43, 37], 
                   [69, 96, 70], [73, 67, 43], [91, 88, 64], 
                   [87, 134, 58], [102, 43, 37], [69, 96, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], [81, 101], [119, 133], 
                    [22, 37], [103, 119], [56, 70], 
                    [81, 101], [119, 133], [22, 37], 
                    [103, 119], [56, 70], [81, 101], 
                    [119, 133], [22, 37], [103, 119]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [84]:
inputs

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])

In [85]:
from torch.utils.data import TensorDataset

In [86]:
train_ds = TensorDataset(inputs, targets)

In [87]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [88]:
from torch.utils.data import DataLoader

In [89]:
batch_size = 5
train_dl = DataLoader(train_ds,batch_size,shuffle=True)

In [90]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    #break

tensor([[ 91.,  88.,  64.],
        [102.,  43.,  37.],
        [ 73.,  67.,  43.],
        [ 69.,  96.,  70.],
        [ 69.,  96.,  70.]])
tensor([[ 81., 101.],
        [ 22.,  37.],
        [ 56.,  70.],
        [103., 119.],
        [103., 119.]])
tensor([[ 87., 134.,  58.],
        [ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 69.,  96.,  70.],
        [ 73.,  67.,  43.]])
tensor([[119., 133.],
        [ 56.,  70.],
        [ 81., 101.],
        [103., 119.],
        [ 56.,  70.]])
tensor([[ 87., 134.,  58.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.]])
tensor([[119., 133.],
        [119., 133.],
        [ 22.,  37.],
        [ 22.,  37.],
        [ 81., 101.]])


In [91]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.1200, -0.4588,  0.3086],
        [ 0.5422,  0.1795, -0.2797]], requires_grad=True)
Parameter containing:
tensor([0.2448, 0.0987], requires_grad=True)


In [92]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.1200, -0.4588,  0.3086],
         [ 0.5422,  0.1795, -0.2797]], requires_grad=True),
 Parameter containing:
 tensor([0.2448, 0.0987], requires_grad=True)]

In [93]:
preds = model(inputs)

In [94]:
preds

tensor([[ -8.4651,  39.6776],
        [ -9.4592,  47.3329],
        [-32.8942,  55.1001],
        [  4.1731,  52.7701],
        [-13.9172,  35.1633],
        [ -8.4651,  39.6776],
        [ -9.4592,  47.3329],
        [-32.8942,  55.1001],
        [  4.1731,  52.7701],
        [-13.9172,  35.1633],
        [ -8.4651,  39.6776],
        [ -9.4592,  47.3329],
        [-32.8942,  55.1001],
        [  4.1731,  52.7701],
        [-13.9172,  35.1633]], grad_fn=<AddmmBackward>)

In [95]:
import torch.nn.functional as F

In [96]:
loss_fn = F.mse_loss

In [98]:
loss = loss_fn(model(inputs), targets)

In [99]:
print(loss)

tensor(6654.3188, grad_fn=<MseLossBackward>)


In [ ]:
opt = torch.optim.SGD()