<a href="https://colab.research.google.com/github/ahmedabdelhameed/PyTorch/blob/master/PyTorch_Basics_Tensors_%26_Gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to PyTorch: Basics


In [ ]:
import torch

In [ ]:
t1 = torch.tensor(4.)
t1


tensor(4.)

In [ ]:
t1.dtype

torch.float32

In [ ]:
t2 = torch.tensor([1., 2., 3., 4.])
t2
t2.dtype

torch.float32

In [ ]:
t3= torch.tensor([[5, 6], [7, 8], [ 9, 10]])
t3

tensor([[ 5,  6],
        [ 7,  8],
        [ 9, 10]])

In [ ]:
t4 = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
t4

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])

In [ ]:
t1.shape

torch.Size([])

In [ ]:
t2.shape

torch.Size([4])

In [ ]:
t3.shape

torch.Size([3, 2])

In [ ]:
t4.shape

torch.Size([2, 2, 3])

In [ ]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4. , requires_grad= True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# Compute derivatives
y.backward()

In [ ]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
y1 = torch.tensor(x)
y1

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [ ]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

In [ ]:
x = torch.rand(5, 3)
print(x)

tensor([[0.3104, 0.0809, 0.9561],
        [0.8084, 0.0052, 0.5424],
        [0.2712, 0.0579, 0.4507],
        [0.5057, 0.0133, 0.6535],
        [0.8945, 0.5813, 0.0829]])


In [ ]:
x = torch.empty(5, 3)
print(x)

tensor([[5.1865e-36, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [0.0000e+00, 5.7397e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [ ]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 2.5312, -2.4006,  0.7204],
        [ 0.8014,  1.3650, -0.6415],
        [ 1.1277,  0.5941, -0.6568],
        [ 0.6811, -1.3374, -0.4127],
        [-2.4437,  0.8633, -1.1585]])


In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 3.5312, -1.4006,  1.7204],
        [ 1.8014,  2.3650,  0.3585],
        [ 2.1277,  1.5941,  0.3432],
        [ 1.6811, -0.3374,  0.5873],
        [-1.4437,  1.8633, -0.1585]], device='cuda:0')
tensor([[ 3.5312, -1.4006,  1.7204],
        [ 1.8014,  2.3650,  0.3585],
        [ 2.1277,  1.5941,  0.3432],
        [ 1.6811, -0.3374,  0.5873],
        [-1.4437,  1.8633, -0.1585]], dtype=torch.float64)


In [ ]:
import torch
dd = torch.te

In [ ]:
y = torch.rand([2,5])
y

tensor([[0.0786, 0.9690, 0.4807, 0.2089, 0.3992],
        [0.1949, 0.5807, 0.3175, 0.8079, 0.6573]])

In [ ]:
y.view(1,10)

tensor([[0.0786, 0.9690, 0.4807, 0.2089, 0.3992, 0.1949, 0.5807, 0.3175, 0.8079,
         0.6573]])

In [ ]:
y = y.view([1,10])
y

tensor([[0.0786, 0.9690, 0.4807, 0.2089, 0.3992, 0.1949, 0.5807, 0.3175, 0.8079,
         0.6573]])

In [ ]:
import torch

# Creating the graph
x = torch.tensor(1.0, requires_grad = True)
y = torch.tensor(2.0)
z = x * y

# Displaying
for i, name in zip([x, y, z], "xyz"):
    print(f"{name}\ndata: {i.data}\nrequires_grad: {i.requires_grad}\n\
grad: {i.grad}\ngrad_fn: {i.grad_fn}\nis_leaf: {i.is_leaf}\n")

x
data: 1.0
requires_grad: True
grad: None
grad_fn: None
is_leaf: True

y
data: 2.0
requires_grad: False
grad: None
grad_fn: None
is_leaf: True

z
data: 2.0
requires_grad: True
grad: None
grad_fn: <MulBackward0 object at 0x7fdf51c78d30>
is_leaf: False



/usr/local/lib/python3.6/dist-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "
